CREATE TABLE IF NOT EXISTS metric
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_metric smallint         NOT NULL,
    value      double precision NOT NULL,
    created_at timestamp        NOT NULL
);
